### ISSUE TITLE
Add a Sponsorship Section

### ISSUE THREAD

**Issue by csinko** [UAHakron/spring-2018-website#10]
First focus of the site is to be seen by sponsors.

We need a section for sponsors to solidify this and a link to our packet, maybe old sponsors?  Also need an email, put sponsors@hakron.io for now.

**Comment by mattertater** [comment]
old sponsors in, now i need to figure out that inverse color thing which I'm PUMPED for.

**Comment by mattertater** [comment]
Yeet the old IBM logo out of there

**Comment by mattertater** [comment]
done done and done
