### ISSUE TITLE
Add info pertaining to basics of event

### ISSUE THREAD

**Issue by csinko** [UAHakron/spring-2018-website#11]
Site should have
When: feb 24-25
Length of Event:
Where: Law Building, University of Akron, Akron Ohio

What:  Want to focus on promoting both software and hardware this event.  Maybe stuff like "For all makers, designers, creators, engineers, programmers" etc.  You can say there will be divisions for software and hardware, need to work on wording though.  Overall should be clear that they are both MAJOR parts of the event, rather than hardware being a minor part historically.  Can mention that this is NEW to make it flashy.

Page should mention it is through the University of Akron - make it clear to someone that isnt local.  Keywords like "Northeast Ohio" to give a reference on Location.

The writeups should have stuff discussing how the event is a learning experience, fun, and can yield prizes.  Focus should be on learning, trying something new, make it not sound so much like a competition like in the past.  This is not crucial to be completed at the current stage, just get some words down (and a place to put them!)  and we will improve them as time progresses.

The focus should be initially not very wordy, and have more words as you scroll down.  That way those who want to read more can do so, but its not in the way for those that dont and can still look clean.

---

This is all of what I have in mind for the final of the website.  I don't expect all of this will be covered at first, but this is a vision / overview.  Feel free to divide some of these into other issues and reference this issue.

**Comment by Lennevia** [comment]
I think I kinda covered this, wording probably needs work in the conciseness department, let me know what you guys think

**Comment by mattertater** [comment]
changed a bit of what rena added, still probably need to put more emphasis on hardware, not sure where though
