### ISSUE TITLE
Sprinkle in some of our historic publicity

### ISSUE THREAD

**Issue by csinko** [UAHakron/spring-2018-website#13]
The news articles we have on us and any other writeups, lets throw them in somewhere on the site for more credibility.

I believe Elissa has this info.

**Comment by mattertater** [comment]
I remember a google docs page that exists that has a couple links in it, somewhere on the drive under sponsorship packet somewhere

**Comment by mattertater** [comment]
found it https://docs.google.com/document/d/1q4qJJgnnNOxzp_4u_cxlFfuRmCHVAlPMH05vWZJnZok/edit#heading=h.3sve73ahh3wh

**Comment by Lennevia** [comment]
Thx friend
