### ISSUE TITLE
Bug: Navbar overlaps content and "more" arrow is faded

### ISSUE THREAD

**Issue by csinko** [UAHakron/spring-2018-website#15]
As shown in image
![image](https://user-images.githubusercontent.com/11744201/33237363-a2d6ee38-d23f-11e7-8dc3-0d40e3b57945.png)

**Comment by mattertater** [comment]
currently working on it and this isn't happening for me, I'll do a quick push to see if it still happens for you

**Comment by mattertater** [comment]
has to do with browser height, only happens when the browser is a good bit wider than it is tall. @julie can test it out with her monitor
